title: Luiz Souza
permalink: "/:year/:month/:day/:title/"

twitter_username: lpsouza
github_username: lpsouza
linkedin_username: lpsouza

theme: minima
plugins:
    - jekyll-feed

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
