title: "Luiz Souza"
description: "DevSecOps. Professor."
permalink: "/:year/:month/:day/:title/"
paginate: 10
paginate_path: "/page/:num/"

twitter_username: lpsouza
github_username: lpsouza
linkedin_username: lpsouza

social:
    github: lpsouza
    linkedin: lpsouza
    instagram: lpsouza
    facebook: lpsouza
    youtube: lpsouza

disqus:
    shortname: luiz-souza

plugins:
    - jekyll-feed
    - jekyll-paginate

sass:
    sass_dir: _sass

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - README.md
    - scripts/
