title: Luiz Souza
permalink: "/:year/:month/:day/:title/"
paginate: 10
paginate_path: "/page/:num/"

twitter_username: lpsouza
github_username: lpsouza
linkedin_username: lpsouza

# theme: minima
plugins:
    - jekyll-feed
    - jekyll-paginate

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
