title: "Luiz Souza"
description: "DevSecOps Specialist"
permalink: "/:year/:month/:day/:title/"

social:
    github: lpsouza
    linkedin: lpsouza
    instagram: lpsouza
    youtube: lpsouza

disqus:
    shortname: luiz-souza

google-analytics: UA-105361937-1

highlighter: rouge

plugins:
    - jekyll-feed
    - jekyll-paginate-v2

sass:
    sass_dir: _sass

pagination:
    enabled: true
    per_page: 10
    permalink: "/page/:num/"
    title: ":title - página :num of :max"
    sort_reverse: true

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - README.md
    - scripts/

prose:
    rooturl: "_posts"
    siteurl: "https://luizsouza.com/"
    media: "media"
    metadata:
        _posts:
            - name: "title"
              field:
                  element: "text"
                  label: "Title"
            - name: "date"
              field:
                  element: "hidden"
                  value: CURRENT_DATETIME
            - name: "author"
              field:
                  element: "hidden"
                  value: CURRENT_USER
            - name: "layout"
              field:
                  element: "hidden"
                  value: "post"
            - name: "category"
              field:
                  element: "select"
                  options:
                      - name: "Tech"
                        value: "Tech"
                      - name: "Games"
                        value: "Games"
                      - name: "Etc"
                        value: "Etc"
            - name: "tags"
              field:
                  element: "multiselect"
                  label: "Tags"
                  alterable: true
            - name: "published"
              field:
                  element: "checkbox"
                  label: "Published"
                  value: true
            - name: "image"
              field:
                  element: "text"
                  label: "Featured image"
                  help: "Optional"
