title: Luiz Souza
author: Luiz Pereira de Souza Filho
email: lpsouza@gmail.com
remote_theme: thelehhman/plainwhite-jekyll
show_excerpts: true
permalink: "/:year/:month/:day/:title/"

exclude:
    - "README.md"
    - ".markdownlink.json"
    - ".editorconfig"
    - ".gitignore"

plainwhite:
    profile_image: https://www.gravatar.com/avatar/ce87a4c115c24ba10709878170134546?s=350
    name: Luiz Pereira de Souza Filho
    tagline: DevSecOps. Professor.
    date_format: "%d/%m/%Y"
    disqus_shortname: luiz-souza
    analytics_id: "UA-105361937-1"
    sitemap: true

    social_links:
        twitter: lpsouza
        github: lpsouza
        linkedIn: in/lpsouza

prose:
    rooturl: "_posts"
    siteurl: "https://luizsouza.com/"
    media: "media"
    metadata:
        _posts:
            - name: "title"
              field:
                  element: "text"
                  label: "title"
            - name: "date"
              field:
                  element: "hidden"
                  value: CURRENT_DATETIME
            - name: "author"
              field:
                  element: "hidden"
                  value: CURRENT_USER
            - name: "layout"
              field:
                  element: "hidden"
                  value: "post"
            - name: "category"
              field:
                  element: "select"
                  options:
                      - name: "Blogging"
                        value: "Blogging"
                      - name: "Tech"
                        value: "Tech"
                      - name: "Linux"
                        value: "Linux"
                      - name: "Games"
                        value: "Games"
            - name: "tags"
              field:
                  element: "multiselect"
                  label: "Add Tags"
                  placeholder: "Choose Tags"
                  alterable: true
