remote_theme: thelehhman/plainwhite-jekyll
show_excerpts: true

exclude: 
    - "README.md"
    - ".markdownlink.json"
    - ".editorconfig"
    - ".gitignore"

plainwhite:
    name: Luiz Pereira de Souza Filho
    tagline: Tecnólogo em Segurança da Informação, consultor em Cloud Computing, desenvolvedor Web-Mobile e professor.
    date_format: "%b %-d, %Y"
    shortname: luiz-souza\
    analytics-id: "UA-105361937-1"
    sitemap: true

    social_links:
        twitter: lpsouza
        github: lpsouza
        linkedIn: in/lpsouza
