title: "Luiz Souza"
description: "DevSecOps Specialist"
author:
    name: "Luiz Pereira de Souza Filho"
    photo: "https://www.gravatar.com/avatar/ce87a4c115c24ba10709878170134546?s=512"
permalink: "/:year/:month/:day/:title/"
paginate: 10
paginate_path: "/page/:num/"
url: "https://luizsouza.com"

social:
    github: lpsouza
    linkedin: lpsouza
    instagram: lpsouza
    twitter: lpsouza
    youtube: lpsouza

disqus:
    shortname: luiz-souza

analytics:
    google: UA-177307059-1
    google-ga4: G-QXL6JNE5NC

highlighter: rouge

plugins:
    - jekyll-feed
    - jekyll-paginate

sass:
    sass_dir: _sass

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - README.md
    - scripts/
