title: Luiz Souza
author: Luiz Pereira de Souza Filho
email: lpsouza@gmail.com
remote_theme: thelehhman/plainwhite-jekyll
show_excerpts: true

exclude:
    - "README.md"
    - ".markdownlink.json"
    - ".editorconfig"
    - ".gitignore"

plainwhite:
    profile_image: https://www.gravatar.com/avatar/ce87a4c115c24ba10709878170134546?s=350
    name: Luiz Pereira de Souza Filho
    tagline: DevSecOps. Professor.
    date_format: "%d/%m/%Y"
    disqus_shortname: luiz-souza
    analytics_id: "UA-105361937-1"
    sitemap: true

    social_links:
        twitter: lpsouza
        github: lpsouza
        linkedIn: in/lpsouza

prose:
  rooturl: '_posts'
  siteurl: 'http://luizsouza.com/'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
